"Flights" Dataset, exploratory analysis -- Miguel Martín González

In [3]:
#install.packages('nycflights13') ## If not already installed
library(nycflights13)

Warning message:
"package 'nycflights13' was built under R version 4.5.3"

In [23]:
 data('flights')
 head(flights , 5)
 summary(flights)

  year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1 2013 1     1   517      515             2         830      819
2 2013 1     1   533      529             4         850      830
3 2013 1     1   542      540             2         923      850
4 2013 1     1   544      545            -1        1004     1022
5 2013 1     1   554      600            -6         812      837
  arr_delay carrier flight tailnum origin dest air_time distance hour minute
1  11       UA      1545   N14228  EWR    IAH  227      1400     5    15
2  20       UA      1714   N24211  LGA    IAH  227      1416     5    29
3  33       AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 -18       B6       725   N804JB  JFK    BQN  183      1576     5    45
5 -25       DL       461   N668DN  LGA    ATL  116       762     6     0
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00

      year          month             day           dep_time    sched_dep_time
 Min.   :2013   Min.   : 1.000   Min.   : 1.00   Min.   :   1   Min.   : 106
 1st Qu.:2013   1st Qu.: 4.000   1st Qu.: 8.00   1st Qu.: 907   1st Qu.: 906
 Median :2013   Median : 7.000   Median :16.00   Median :1401   Median :1359
 Mean   :2013   Mean   : 6.549   Mean   :15.71   Mean   :1349   Mean   :1344
 3rd Qu.:2013   3rd Qu.:10.000   3rd Qu.:23.00   3rd Qu.:1744   3rd Qu.:1729
 Max.   :2013   Max.   :12.000   Max.   :31.00   Max.   :2400   Max.   :2359
                                                 NA's   :8255
   dep_delay          arr_time    sched_arr_time   arr_delay
 Min.   : -43.00   Min.   :   1   Min.   :   1   Min.   : -86.000
 1st Qu.:  -5.00   1st Qu.:1104   1st Qu.:1124   1st Qu.: -17.000
 Median :  -2.00   Median :1535   Median :1556   Median :  -5.000
 Mean   :  12.64   Mean   :1502   Mean   :1536   Mean   :   6.895
 3rd Qu.:  11.00   3rd Qu.:1940   3rd Qu.:1945   3rd Qu.:  14.000
 Max.   :1301.00   Max.   :2400   Max.   :2359   Max.   :1272.000
 NA's   :8255      NA's   :8713                  NA's   :9430
   carrier              flight       tailnum             origin
 Length:336776      Min.   :   1   Length:336776      Length:336776
 Class :character   1st Qu.: 553   Class :character   Class :character
 Mode  :character   Median :1496   Mode  :character   Mode  :character
                    Mean   :1972
                    3rd Qu.:3465
                    Max.   :8500

     dest              air_time        distance         hour
 Length:336776      Min.   : 20.0   Min.   :  17   Min.   : 1.00
 Class :character   1st Qu.: 82.0   1st Qu.: 502   1st Qu.: 9.00
 Mode  :character   Median :129.0   Median : 872   Median :13.00
                    Mean   :150.7   Mean   :1040   Mean   :13.18
                    3rd Qu.:192.0   3rd Qu.:1389   3rd Qu.:17.00
                    Max.   :695.0   Max.   :4983   Max.   :23.00
                    NA's   :9430
     minute        time_hour
 Min.   : 0.00   Min.   :2013-01-01 05:00:00
 1st Qu.: 8.00   1st Qu.:2013-04-04 13:00:00
 Median :29.00   Median :2013-07-03 10:00:00
 Mean   :26.23   Mean   :2013-07-03 05:22:54
 3rd Qu.:44.00   3rd Qu.:2013-10-01 07:00:00
 Max.   :59.00   Max.   :2013-12-31 23:00:00

In [44]:
unique(flights$origin)
unique(flights$year)
unique(flights$carrier)
#unique(flights$tailnum)
#unique(flights$dest)
#unique(flights$flight)
#head(flights[flights$tailnum == "N804JB" , ] )
print(colnames(flights))

[1] "EWR" "LGA" "JFK"

[1] 2013

 [1] "UA" "AA" "B6" "DL" "EV" "MQ" "US" "WN" "VX" "FL" "AS" "9E" "F9" "HA" "YV"
[16] "OO"

 [1] "year"           "month"          "day"            "dep_time"
 [5] "sched_dep_time" "dep_delay"      "arr_time"       "sched_arr_time"
 [9] "arr_delay"      "carrier"        "flight"         "tailnum"
[13] "origin"         "dest"           "air_time"       "distance"
[17] "hour"           "minute"         "time_hour"

In [36]:
#sum(!complete.cases(flights))
sum(is.na(flights$dep_delay))
sum(is.na(flights$arr_delay))
sum(is.na(flights$air_time))
sum(is.na(flights$dep_time))
sum(is.na(flights$sched_dep_time))

[1] 8255

[1] 9430

[1] 9430

[1] 8255

[1] 0

In [43]:
nyflights = flights
nyflights$year = NULL
head(nyflights)

  month day dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay
1 1     1   517      515             2         830      819            11
2 1     1   533      529             4         850      830            20
3 1     1   542      540             2         923      850            33
4 1     1   544      545            -1        1004     1022           -18
5 1     1   554      600            -6         812      837           -25
6 1     1   554      558            -4         740      728            12
  carrier flight tailnum origin dest air_time distance hour minute
1 UA      1545   N14228  EWR    IAH  227      1400     5    15
2 UA      1714   N24211  LGA    IAH  227      1416     5    29
3 AA      1141   N619AA  JFK    MIA  160      1089     5    40
4 B6       725   N804JB  JFK    BQN  183      1576     5    45
5 DL       461   N668DN  LGA    ATL  116       762     6     0
6 UA      1696   N39463  EWR    ORD  150       719     5    58
  time_hour
1 2013-01-01 05:00:00
2 2013-01-01 05:00:00
3 2013-01-01 05:00:00
4 2013-01-01 05:00:00
5 2013-01-01 06:00:00
6 2013-01-01 05:00:00